# Generated by Django 4.1.13 on 2023-12-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
