# Generated by Django 4.1.13 on 2023-12-11 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='user_photos/')),
                ('aadhar', models.CharField(max_length=12)),
                ('aadhar_photo', models.ImageField(upload_to='aadhar_photos/')),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('license_id', models.CharField(blank=True, max_length=20, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='license_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='user',
        ),
        migrations.DeleteModel(
            name='Advocate',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
