# Generated by Django 4.1.13 on 2023-12-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_moreinfo_remove_client_user_remove_judge_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moreinfo',
            name='user',
        ),
    ]
