# Generated by Django 5.0 on 2023-12-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_moreinfo_remove_client_user_remove_judge_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoreInfo',
        ),
    ]
