# Generated by Django 5.0 on 2023-12-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoreInfo',
        ),
    ]
