# Generated by Django 5.0 on 2023-12-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0010_delete_moreinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='user_photos/')),
                ('aadhar', models.CharField(max_length=12)),
                ('aadhar_photo', models.ImageField(upload_to='aadhar_photos/')),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('license_id', models.CharField(blank=True, max_length=20, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='license_photos/')),
            ],
        ),
    ]
