# Generated by Django 5.0 on 2023-12-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('license_id', models.CharField(blank=True, max_length=20, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
